In [1]:
import numpy as np


In [3]:
# Sumas de arrays
array1 = np.array([1, 2, 3])
array2 = np.array([[6], [10], [20], [30]])

suma = array1 + array2
print(suma)

[[ 7  8  9]
 [11 12 13]
 [21 22 23]
 [31 32 33]]


In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


In [6]:
resultado = np.add(a, b)
print(resultado)

resultado = np.subtract(a, b)
print(resultado)

resultado = np.multiply(a, b)
print(resultado)

resultado = np.divide(a, b)
print(resultado)


[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [7]:
resultado2 = np.exp(a)
print(resultado2)

resultado3 = np.sqrt(a)
print(resultado3)

resultado4 = np.sin(a)
print(resultado4)

resultado5 = np.log(a)
print(resultado5)


[ 2.71828183  7.3890561  20.08553692]
[1.         1.41421356 1.73205081]
[0.84147098 0.90929743 0.14112001]
[0.         0.69314718 1.09861229]
